### ISSUE TITLE
support cuda toolkit 11.7 and driver 12.1

### ISSUE THREAD

**Issue by sammilei** [cyrusbehr/tensorrt-cpp-api#45]
Thanks for the code base! I was able to run it with cuda toolkit 12.1. However, I would need to use it on 11.7. `TensorRT-8.6.1.6` requests these lib in version 12. I also tried to soft link these to 11 but the it didn't get through.
```
libcublas.so.12 => not found
libcublasLt.so.12 => not found
```
I saw your previous version uses `TensorRT-8.2.1.8` but that is for up to cuda 11.5. 

Thank you in advance for any suggestions!

**Comment by cyrusbehr** [comment]
I'm confused about your question. 
You can download TensorRT 8.6 for CUDA 11.x. That version does not require CUDA 12.

![image](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/17056751/6798b2dd-e49d-4f46-a997-000ecd3ce158)

**Comment by cyrusbehr** [comment]
It could be something with your environment. I don't have CUDA 12 installed on my system and it works fine.

**Comment by sammilei** [comment]
Thanks! Can you show what driver version do you use?

**Comment by sammilei** [comment]
I solved the problem. I removed the `nvidia-tensorrt` and reinstalled with cuda 11.7. I started with 12.1 as toolkit for the `nvidia-tensorrt`.

**Comment by cyrusbehr** [comment]
I assumed that was the issue. Glad you resolved it.
